/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/exception/403.vue')['default']
    404: typeof import('./src/components/exception/404.vue')['default']
    500: typeof import('./src/components/exception/500.vue')['default']
    Buttons: typeof import('./src/components/exception/buttons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KevyEmpty: typeof import('./src/components/kevy-empty/components/kevy-empty/kevy-empty.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    Router: typeof import('./src/components/layout/Router.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
  }
}
